# NumPy - Counting, Sorting, Searching, and Copy vs View 

### Counting Functions in NumPy

In [3]:
import numpy as np

# Creating a NumPy array

a = np.array([1, 0, 2, 0, 3, 2, 2, 2])
b = np.array([4, 5, 6])

In [5]:
# Count the non-zero elements in the array

print("Non-zero count:", np.count_nonzero(a))

Non-zero count: 6


In [7]:
# Find unique elements in the array

print("Unique elements:", np.unique(a))

Unique elements: [0 1 2 3]


In [9]:
# Count the frequency of each unique value in the array using bincount()
# (Index represents the value, and value at that index represents its frequency)

print("Frequency count (bincount):", np.bincount(a))

Frequency count (bincount): [2 1 4 1]


In [11]:
# Cumulative sum of elements

print("Cumulative sum:", np.cumsum(a))

Cumulative sum: [ 1  1  3  3  6  8 10 12]


In [13]:
# Cumulative product of elements

print("Cumulative product:", np.cumprod(a))

Cumulative product: [1 0 0 0 0 0 0 0]


### Sorting in NumPy

In [16]:
# Sorting in one-dimensional and two-dimensional arrays
ar = np.array([
    [1, 2, 3],
    [3, 4, 2],
    [7, 5, 6]
])

In [18]:
# Sorting in one-dimensional and two-dimensional arrays

ar = np.array([
    [1, 2, 3],
    [3, 4, 2],
    [7, 5, 6]
])

In [20]:
# Sort along columns (axis=0)

sorted_arr = np.sort(ar, axis=0)
print("Sorted array along columns:\n", sorted_arr)

Sorted array along columns:
 [[1 2 2]
 [3 4 3]
 [7 5 6]]


In [22]:
# argsort() - Returns the indices that would sort the array

ar = np.array([7, 4, 6, 5, 8, 1, 2, 4])
print("Sorted array:", np.sort(ar))
print("Indices for sorting:", np.argsort(ar))

Sorted array: [1 2 4 4 5 6 7 8]
Indices for sorting: [5 6 1 7 3 2 0 4]


In [24]:
# searchsorted() - Find the index to insert an element in a sorted array

ar = np.array([1, 2, 4, 5, 7, 8])
print("Index to insert 6:", np.searchsorted(ar, 6))

Index to insert 6: 4


In [26]:
# partition() - Rearrange elements so that the k-th smallest element is in its correct position

ar = np.array([4, 5, 2, 1, 7, 8, 3])
print("Partitioned array:", np.partition(ar, 3))
print("Indices of partitioned elements:", np.argpartition(ar, 3))

Partitioned array: [2 1 3 4 5 8 7]
Indices of partitioned elements: [2 3 6 0 1 5 4]


### Searching in NumPy

In [29]:
# where() and argwhere() - Find indices where a condition is met

ar = np.array([1, 5, 4, 7, 2, 8, 3])
indices = np.where(ar > 3)
print("Indices where elements > 3 (where):", indices)

Indices where elements > 3 (where): (array([1, 2, 3, 5], dtype=int64),)


In [31]:
indices_argwhere = np.argwhere(ar > 3)
print("Indices where elements > 3 (argwhere):", indices_argwhere)

Indices where elements > 3 (argwhere): [[1]
 [2]
 [3]
 [5]]


In [33]:
# Find indices of non-zero elements

ar = np.array([0, 1, 5, 4, 7, 2, 8, 3, 0])
print("Indices of non-zero elements:", np.nonzero(ar))

Indices of non-zero elements: (array([1, 2, 3, 4, 5, 6, 7], dtype=int64),)


In [35]:
# extract() - Extract elements that satisfy a condition

extracted = np.extract(ar > 3, ar)
print("Elements > 3 (extract):", extracted)

Elements > 3 (extract): [5 4 7 8]


### Filtration in NumPy

In [38]:
# Boolean indexing

ar = np.array([0, 1, 5, 4, 7, 2, 8, 3, 0])
print("Elements > 5 (Boolean indexing):", ar[ar > 5])

Elements > 5 (Boolean indexing): [7 8]


In [40]:
# where() with masking

new_arr = np.where(ar > 3, ar, 0)  # Replace elements <= 3 with 0
print("Masked array (where):", new_arr)

Masked array (where): [0 0 5 4 7 0 8 0 0]


In [42]:
# compress() - Filter elements using a boolean mask

compressed = np.compress(ar < 3, ar)
print("Filtered elements (compress):", compressed)

Filtered elements (compress): [0 1 2 0]


### View in NumPy

In [45]:
# View creation using slicing

ar = np.array([3, 4, 8, 2, 1, 7, 5, 6])
view = ar[1:4]
print("Original array:", ar)
print("View (slice):", view)

Original array: [3 4 8 2 1 7 5 6]
View (slice): [4 8 2]


In [47]:
# Modifying the view affects the original array

view[1] = 1
print("Original array after modifying view:", ar)

Original array after modifying view: [3 4 1 2 1 7 5 6]


In [49]:
# View creation using transpose

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
view = arr.T  # Creates a transposed view
print("Transposed view:\n", view)

Transposed view:
 [[1 4]
 [2 5]
 [3 6]]


In [51]:
# View creation using reshape

ar = np.array([1, 2, 5, 3, 6, 4, 8, 7])
view = ar.reshape(4, 2)
print("Reshaped view:\n", view)

Reshaped view:
 [[1 2]
 [5 3]
 [6 4]
 [8 7]]


### Copy in NumPy

In [54]:
# Copy function

ar = np.array([1, 2, 4, 5, 6])
print("Original array:", ar)

Original array: [1 2 4 5 6]


In [56]:
# Create a copy

arr_copy = ar.copy()
arr_copy[1] = 3  # Modify the copy
print("Original array after modifying copy:", ar)
print("Modified copy:", arr_copy)

Original array after modifying copy: [1 2 4 5 6]
Modified copy: [1 3 4 5 6]


In [58]:
# Fancy Indexing (Copy)

ar = np.array([1, 2, 4, 5, 6])
i = [3, 0, 1]  # Indices to extract elements
new_arr = ar[i]  # Creates a copy of the selected elements
new_arr[:2] = [1, 2]  # Modify the copy
print("Original array after fancy indexing:", ar)

Original array after fancy indexing: [1 2 4 5 6]


In [60]:
# Boolean Indexing (Copy)

ar = np.array([1, 2, 4, 5, 6])
new_ar = ar[ar < 5]  # Extracts elements less than 5 (creates a copy)
print("Original array:", ar)
print("Boolean-indexed copy before modification:", new_ar)

Original array: [1 2 4 5 6]
Boolean-indexed copy before modification: [1 2 4]


In [62]:
# Modifying the boolean-indexed copy

new_ar[2] = 3
print("Modified copy:", new_ar)
print("Original array remains unchanged:", ar)

Modified copy: [1 2 3]
Original array remains unchanged: [1 2 4 5 6]
